"""add technicians table and job-technician relationship

Revision ID: 33d521c4b1cf
Revises: bf70f984e3b6
Create Date: 2026-09-04 18:06:12.727353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d521c4b1cf'
down_revision: Union[str, Sequence[str], None] = 'bf70f984e3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('available', 'busy', 'off_duty', name='technicianstatus'), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('jobs', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('jobs', sa.Column('technician_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'technicians', ['technician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'technician_id')
    op.drop_column('jobs', 'longitude')
    op.drop_column('jobs', 'latitude')
    op.drop_table('technicians')
    # ### end Alembic commands ###
