"""replace pickup/dropoff with site_address and description

Revision ID: bf70f984e3b6
Revises: 5267851dd089
Create Date: 2026-07-14 16:02:27.736631

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf70f984e3b6'
down_revision: Union[str, Sequence[str], None] = '5267851dd089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('site_address', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('description', sa.String(length=1000), nullable=False))
    op.drop_column('jobs', 'dropoff_address')
    op.drop_column('jobs', 'pickup_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('pickup_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('dropoff_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'site_address')
    # ### end Alembic commands ###
